"""empty message

Revision ID: 017dfd6eb476
Revises: ef7042e11e1c
Create Date: 2021-10-14 17:32:00.139670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017dfd6eb476'
down_revision = 'ef7042e11e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.drop_constraint('bot_command_value_key', 'bot_command', type_='unique')
    op.drop_column('bot_command', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_command', sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('bot_command_value_key', 'bot_command', ['value'])
    op.drop_table('tg_button')
    # ### end Alembic commands ###
