"""username field in TelegramUser

Revision ID: 4bc5c83e0d5a
Revises: 830deac9e778
Create Date: 2021-12-30 17:16:26.641403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc5c83e0d5a'
down_revision = '830deac9e778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_user', sa.Column('username', sa.String(length=100), nullable=True))
    op.drop_column('telegram_user', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_user', sa.Column('user_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('telegram_user', 'username')
    # ### end Alembic commands ###
