"""add relationship Bot with TelegramUser

Revision ID: 830deac9e778
Revises: b675b82c552a
Create Date: 2021-12-28 17:04:50.262093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830deac9e778'
down_revision = 'b675b82c552a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_user', sa.Column('bot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'telegram_user', 'bot', ['bot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_user', type_='foreignkey')
    op.drop_column('telegram_user', 'bot_id')
    # ### end Alembic commands ###
