"""add Script model

Revision ID: 9423563d870c
Revises: b8d2fc6d0d55
Create Date: 2022-04-25 15:43:36.856830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9423563d870c'
down_revision = 'b8d2fc6d0d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bot', sa.Column('script_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bot', 'script', ['script_id'], ['id'])
    op.add_column('state', sa.Column('script_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'state', 'script', ['script_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'state', type_='foreignkey')
    op.drop_column('state', 'script_id')
    # op.drop_constraint(None, 'bot', type_='foreignkey')
    op.drop_column('bot', 'script_id')
    op.drop_table('script')
    # ### end Alembic commands ###
