"""add input types

Revision ID: b8d2fc6d0d55
Revises: 3a4823e0e992
Create Date: 2022-04-04 16:23:08.040316

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy import String, Column
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = 'b8d2fc6d0d55'
down_revision = '3a4823e0e992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    data_upgrades()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    data_downgrades()
    # ### end Alembic commands ###


def data_upgrades():
    input_types_table = table('input_types', column('value', String(100)))
    op.bulk_insert(input_types_table, 
        [
            {'value':'text'},
            {'value':'location'},
            {'value':'phone'},
            {'value':'callback'}
        ]
    )

def data_downgrades():
     op.execute("delete from input_types")
