"""Delete models

Revision ID: cae138748a0a
Revises: 4bc5c83e0d5a
Create Date: 2022-03-03 12:52:42.105663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae138748a0a'
down_revision = '4bc5c83e0d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reply_button_has_view')
    op.drop_table('command')
    op.drop_table('replybutton')
    op.drop_constraint('callback_func_name_key', 'callback', type_='unique')
    op.drop_column('callback', 'func_name')
    op.add_column('input', sa.Column('type_id', sa.Integer(), nullable=True))
    op.add_column('input', sa.Column('InputTypes', sa.NullType(), nullable=True, back_populates='inputs'))
    op.drop_constraint('input_command_id_fkey', 'input', type_='foreignkey')
    op.drop_constraint('input_replybutton_id_fkey', 'input', type_='foreignkey')
    op.create_foreign_key(None, 'input', 'input_types', ['type_id'], ['id'])
    op.drop_column('input', 'type')
    op.drop_column('input', 'replybutton_id')
    op.drop_column('input', 'command_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input', sa.Column('command_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('input', sa.Column('replybutton_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('input', sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'input', type_='foreignkey')
    op.create_foreign_key('input_replybutton_id_fkey', 'input', 'replybutton', ['replybutton_id'], ['id'])
    op.create_foreign_key('input_command_id_fkey', 'input', 'command', ['command_id'], ['id'])
    op.drop_column('input', 'InputTypes')
    op.drop_column('input', 'type_id')
    op.add_column('callback', sa.Column('func_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('callback_func_name_key', 'callback', ['func_name'])
    op.create_table('replybutton',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('replybutton_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='replybutton_pkey'),
    sa.UniqueConstraint('value', name='replybutton_value_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('command',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='command_pkey'),
    sa.UniqueConstraint('value', name='command_value_key')
    )
    op.create_table('reply_button_has_view',
    sa.Column('replybutton_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('view_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['replybutton_id'], ['replybutton.id'], name='reply_button_has_view_replybutton_id_fkey'),
    sa.ForeignKeyConstraint(['view_id'], ['view.id'], name='reply_button_has_view_view_id_fkey'),
    sa.PrimaryKeyConstraint('replybutton_id', 'view_id', name='reply_button_has_view_pkey')
    )
    op.drop_table('input_types')
    # ### end Alembic commands ###
